CREATE TABLE bilerny (
    `car_id` INTEGER PRIMARY KEY AUTO_INCREMENT,
`makemodel`		varchar(200),
`prices`		varchar(200),
`forhandler`	varchar(200),
`modelår` 		varchar(10),
`f_reg` 		varchar(10),
`km_tal` 		varchar(20),
`drivmiddel` 	varchar(20),
`bs_forbrug` 	varchar(20),
`CO2` 			varchar(20),
`periodisk_afg` varchar(50),
`ydelse` 		varchar(50),
`tophastighed` 	varchar(50),
`geartype` 		varchar(50),
`trækvægt` 		varchar(50),
`nypris`		varchar(50),
`kategori`		varchar(50),
`type`			varchar(20),
`vægt`			varchar(50),
`bredde`		varchar(50),
`længde`		varchar(50),
`højde`			varchar(50),
`lastevne`		varchar(50),
`max_træk_m_b`	varchar(50),
`trækhjul`		varchar(20),
`abs_brems`		varchar(50),
`tank_kap`		varchar(20),
`døre`			varchar(10),
`beskrivelse`	varchar(5000),
`cvr`			varchar(20)
);